- name: start php-fpm
  service:
    name: php-fpm
    enabled: yes
    state: started
  sudo: yes

- name: restart php-fpm
  service:
    name: php-fpm
    enabled: yes
    state: restarted
  sudo: yes

